"""Turn a lock file into CMake glue plus an xparameters-style instance header.

The generated .cmake file is the only thing the project's CMakeLists has to
include.  It declares one source per (IP, version) -- FetchContent for git and
archive sources, a plain add_subdirectory for path sources -- and collects the
driver targets behind a single interface library, `ipman::drivers`.

Driver contract: a driver package is a directory with a CMakeLists.txt that
defines the target named in the lock (by default ipdrv_<ipname>).  Before the
directory is added these variables are set for it:

    IPMAN_DRIVER_NAME        pwm_ctrl
    IPMAN_DRIVER_IP_VERSION  1.2
    IPMAN_DRIVER_TARGET      ipdrv_pwm_ctrl
    IPMAN_DRIVER_INSTANCES   pwm_ctrl_0;pwm_ctrl_1
"""
from __future__ import annotations

import re
from pathlib import Path

from .gitref import can_shallow_clone, classify


def _cm_str(value) -> str:
    """Quote a value for CMake, escaping backslashes and quotes."""
    text = "" if value is None else str(value)
    return '"%s"' % text.replace("\\", "/").replace('"', '\\"')


def _c_ident(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", name).upper()


def generate_cmake(lock: dict, header_path=None) -> str:
    L = []
    a = L.append
    a("# Generated by %s on %s -- do not edit." % (lock["generator"], lock["generated"]))
    a("# Source: %s (driver database v%s)" % (lock["source"]["file"], lock["db_version"]))
    a("include_guard(GLOBAL)")
    a("include(FetchContent)")
    a("")
    a("set(IPMAN_DB_VERSION %s)" % _cm_str(lock["db_version"]))
    a("set(IPMAN_XSA_SHA256 %s)" % _cm_str(lock["source"].get("sha256", "")))
    a("set(IPMAN_DRIVER_TARGETS %s)" % _cm_str(";".join(d["target"] for d in lock["drivers"])))
    a("")

    if lock["unresolved"]:
        for u in lock["unresolved"]:
            a("message(WARNING \"ipman: no driver for %s %s (instances: %s) - %s\")"
              % (u["ip"], u["ip_version"], ", ".join(u["instances"]),
                 u["reason"].replace('"', "'")))
        a("")

    for d in lock["drivers"]:
        src = d["source"]
        fetch_name = "ipman_" + re.sub(r"[^A-Za-z0-9_]", "_", d["target"])
        a("# ---------------------------------------------------------------")
        a("# %s  version %s  (rule %s)" % (d["ip"], d["ip_version"], d["matched"]))
        if d["summary"]:
            a("# %s" % d["summary"])
        a("# instances: %s" % ", ".join(i["instance"] for i in d["instances"]))
        a("set(IPMAN_DRIVER_NAME %s)" % _cm_str(d["ip"].split(":")[-1]))
        a("set(IPMAN_DRIVER_IP_VERSION %s)" % _cm_str(d["ip_version"]))
        a("set(IPMAN_DRIVER_TARGET %s)" % _cm_str(d["target"]))
        a("set(IPMAN_DRIVER_INSTANCES %s)"
          % _cm_str(";".join(i["instance"] for i in d["instances"])))

        if src["type"] == "path":
            path = src["uri"]
            if src.get("subdir"):
                path = "%s/%s" % (path.rstrip("/"), src["subdir"].strip("/"))
            a("if(NOT EXISTS %s)" % _cm_str(path.rstrip("/") + "/CMakeLists.txt"))
            a("  message(FATAL_ERROR \"ipman: driver for %s not found at %s\")"
              % (d["ip"], path))
            a("endif()")
            a("add_subdirectory(%s %s)"
              % (_cm_str(path), _cm_str("${CMAKE_BINARY_DIR}/ipman/drivers/" + d["target"])))
        else:
            a("FetchContent_Declare(%s" % fetch_name)
            if src["type"] == "git":
                a("  GIT_REPOSITORY %s" % _cm_str(src["uri"]))
                ref = src.get("ref") or ""
                if ref:
                    kind = classify(ref, src.get("ref_type"))
                    a("  GIT_TAG %s  # %s" % (_cm_str(ref), kind))
                    # A commit cannot be fetched by name with --depth 1; asking
                    # for it produces an opaque clone failure, so only shallow
                    # clone tags and branches.
                    if can_shallow_clone(ref, src.get("ref_type")):
                        a("  GIT_SHALLOW TRUE")
                a("  GIT_SUBMODULES_RECURSE TRUE")
            else:
                a("  URL %s" % _cm_str(src["uri"]))
                if src.get("sha256"):
                    a("  URL_HASH %s" % _cm_str("SHA256=" + src["sha256"]))
            if src.get("subdir"):
                a("  SOURCE_SUBDIR %s" % _cm_str(src["subdir"]))
            a(")")
            a("FetchContent_MakeAvailable(%s)" % fetch_name)

        a("if(NOT TARGET %s)" % d["target"])
        a("  message(FATAL_ERROR \"ipman: driver package for %s did not define "
          "target %s. Check the 'target' field in the driver database.\")"
          % (d["ip"], d["target"]))
        a("endif()")
        a("")

    a("# ---------------------------------------------------------------")
    a("# One target to link them all.")
    a("add_library(ipman_drivers INTERFACE)")
    a("add_library(ipman::drivers ALIAS ipman_drivers)")
    for d in lock["drivers"]:
        a("target_link_libraries(ipman_drivers INTERFACE %s)" % d["target"])
    if header_path:
        a("target_include_directories(ipman_drivers INTERFACE %s)"
          % _cm_str(Path(header_path).resolve().parent.as_posix()))
    a("")
    return "\n".join(L) + "\n"


def generate_header(manifest: dict, lock: dict, guard: str = "IPMAN_IPS_H") -> str:
    driver_of = {}
    for d in lock["drivers"]:
        for inst in d["instances"]:
            driver_of[inst["instance"]] = d["target"]

    rows = [ip for ip in manifest["ips"] if ip["custom"]]
    L = []
    a = L.append
    a("/* Generated by %s on %s -- do not edit." % (lock["generator"], lock["generated"]))
    a(" * Source: %s" % manifest["source"]["file"])
    a(" */")
    a("#ifndef %s" % guard)
    a("#define %s" % guard)
    a("")
    a("#ifdef __cplusplus")
    a("extern \"C\" {")
    a("#endif")
    a("")
    a("#define IPMAN_XSA_FILE       \"%s\"" % manifest["source"]["file"])
    a("#define IPMAN_DB_VERSION     \"%s\"" % lock["db_version"])
    a("#define IPMAN_IP_COUNT       %d" % len(rows))
    a("")
    a("/* Per-instance address defines, in the style of xparameters.h. */")
    for ip in rows:
        ident = _c_ident(ip["instance"])
        if ip["base_address"]:
            a("#define %-28s %sUL" % (ident + "_BASEADDR", ip["base_address"]))
        if ip["high_address"]:
            a("#define %-28s %sUL" % (ident + "_HIGHADDR", ip["high_address"]))
    a("")
    a("typedef struct {")
    a("    const char    *instance;   /* block design instance name   */")
    a("    const char    *vlnv;       /* vendor:library:name:version  */")
    a("    const char    *driver;     /* CMake driver target, or \"\"   */")
    a("    unsigned long  base_addr;")
    a("    unsigned long  high_addr;")
    a("} ipman_ip_info_t;")
    a("")
    a("/* One copy per translation unit; small and read-only. */")
    a("static const ipman_ip_info_t IPMAN_IPS[IPMAN_IP_COUNT > 0 ? IPMAN_IP_COUNT : 1] = {")
    for ip in rows:
        a("    { \"%s\", \"%s\", \"%s\", %sUL, %sUL }," % (
            ip["instance"], ip["vlnv"], driver_of.get(ip["instance"], ""),
            ip["base_address"] or "0x0", ip["high_address"] or "0x0"))
    if not rows:
        a("    { 0, 0, 0, 0UL, 0UL }")
    a("};")
    a("")
    a("#ifdef __cplusplus")
    a("}  /* extern \"C\" */")
    a("#endif")
    a("")
    a("#endif /* %s */" % guard)
    return "\n".join(L) + "\n"
