"""Generate the runtime register-map union from the driver records.

Build-time resolution picks *a driver*; this picks *a register layout*, at
runtime, from what the hardware actually reports. The two are different
questions whenever one software image has to run against more than one
bitstream revision -- a field-updated FPGA, or one image across a board family.

The generated header gives each IP:

    namespace ipman::pwm_ctrl {
        using Map = std::variant<acme::PwmCtrlV1, acme::PwmCtrlV2>;
        Probe probe(std::uintptr_t base);          // reads the ID register
        std::optional<Map> bind(std::uintptr_t base);
        const char *map_name(const Map &);
    }

`bind` reads the ID register at its fixed offset, checks the magic, decodes
major/minor, and constructs the alternative whose `match` covers that version.
The version tests are compiled from the driver manifest, so the manifest stays
the single source of truth rather than the rule being restated in C++.

A register-map type only has to provide two things:

    static std::uint32_t read_word(std::uintptr_t base, std::size_t offset);
    explicit Map(std::uintptr_t base);

`read_word` is deliberately the driver's job: it is the one piece that knows
whether this build talks to real MMIO or a simulation backing store.
"""
from __future__ import annotations

import re

from . import __version__
from .util import IpmanError, utc_now

GUARD = "IPMAN_MAPS_HPP"


def _ns(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def _mask(bits) -> int:
    msb, lsb = bits
    return ((1 << (msb - lsb + 1)) - 1) << lsb


def _extract(expr: str, bits) -> str:
    msb, lsb = bits
    width = msb - lsb + 1
    shifted = expr if lsb == 0 else "(%s >> %d)" % (expr, lsb)
    if width == 32:
        return shifted
    return "(%s & 0x%Xu)" % (shifted, (1 << width) - 1)


def version_test(match: str) -> str:
    """Compile a database-style match pattern into a C++ condition on `v`."""
    if match == "*":
        return "true"
    if match.endswith(".*") and match[:-2].isdigit():
        return "v.major == %s" % match[:-2]
    parts = match.split(".")
    if len(parts) == 2 and all(p.isdigit() for p in parts):
        return "(v.major == %s && v.minor == %s)" % (parts[0], parts[1])
    raise IpmanError(
        "cannot express match %r as a runtime version test. Runtime dispatch "
        "supports an exact version ('1.2'), a major glob ('1.*') or '*'; use one "
        "of those on any implements entry that declares a map." % match)


def collect(records: list) -> list:
    """Group driver records into one dispatch group per IP."""
    groups: dict = {}
    order: list = []
    for record in records:
        if record.get("status") != "ok" or not record.get("maps"):
            continue
        key = record["ip"]
        if key not in groups:
            groups[key] = {
                "ip": key,
                "name": record["ip_name"],
                "built_for": record["ip_version"],
                "id_register": record["id_register"],
                "maps": [],
                "drivers": [],
            }
            order.append(key)
        group = groups[key]

        if record["id_register"] != group["id_register"]:
            raise IpmanError(
                "drivers for %s disagree about the ID register layout. Every "
                "revision must report its version the same way, or there is no "
                "way to read it before the revision is known." % key)

        group["drivers"].append(record["target"])
        seen = {m["type"] for m in group["maps"]}
        for mapping in record["maps"]:
            if mapping["type"] not in seen:
                group["maps"].append(mapping)
                seen.add(mapping["type"])
    return [groups[k] for k in order]


def generate(records: list, db_version: str = "") -> str:
    groups = collect(records)

    L = []
    a = L.append
    a("/* Generated by ipman %s on %s -- do not edit." % (__version__, utc_now()))
    a(" *")
    a(" * Runtime register-map selection. Each IP below is probed at its ID")
    a(" * register and bound to the layout matching the version the hardware")
    a(" * reports, which need not be the version this build was configured for.")
    a(" */")
    a("#ifndef %s" % GUARD)
    a("#define %s" % GUARD)
    a("")
    a("#include <cstddef>")
    a("#include <cstdint>")
    a("#include <optional>")
    a("#include <variant>")
    a("")
    headers = []
    for group in groups:
        for mapping in group["maps"]:
            if mapping["header"] not in headers:
                headers.append(mapping["header"])
    for header in headers:
        a('#include "%s"' % header)
    if headers:
        a("")
    a("/* Lets an application compile whether or not an IP is in the design. */")
    for group in groups:
        a("#define IPMAN_HAS_%s 1" % _ns(group["name"]).upper())
    a("")
    a("namespace ipman {")
    a("")
    a("struct IpVersion {")
    a("    std::uint8_t major = 0;")
    a("    std::uint8_t minor = 0;")
    a("};")
    a("")
    a("inline bool operator==(IpVersion a, IpVersion b) {")
    a("    return a.major == b.major && a.minor == b.minor;")
    a("}")
    a("inline bool operator!=(IpVersion a, IpVersion b) { return !(a == b); }")
    a("")
    a("struct Probe {")
    a("    bool          valid = false;  /* the magic field matched */")
    a("    std::uint32_t raw   = 0;      /* the ID register, verbatim  */")
    a("    IpVersion     version{};")
    a("};")
    a("")

    if not groups:
        a("/* No driver declared a register map with an ID register, so there is")
        a(" * nothing to dispatch on. Drivers opt in by adding 'map' and")
        a(" * 'id_register' to their ipman-driver.json. */")
        a("")
    if db_version:
        a('inline constexpr const char *kDriverDbVersion = "%s";' % db_version)
        a("")

    for group in groups:
        idr = group["id_register"]
        ns = _ns(group["name"])
        types = [m["type"] for m in group["maps"]]

        a("/* ------------------------------------------------------------------")
        a(" * %s" % group["ip"])
        a(" * configured from this bitstream at version %s" % group["built_for"])
        a(" * driver package(s): %s" % ", ".join(group["drivers"]))
        a(" * ID register at offset 0x%02X, magic 0x%X in bits [%d:%d]"
          % (idr["offset"], idr["magic_value"],
             idr["magic_bits"][0], idr["magic_bits"][1]))
        a(" * ---------------------------------------------------------------- */")
        a("namespace %s {" % ns)
        a("")
        a("inline constexpr std::size_t   kIdOffset   = 0x%02X;" % idr["offset"])
        a("inline constexpr std::uint32_t kIdMagic    = 0x%Xu;" % idr["magic_value"])
        a('inline constexpr const char   *kBuiltFor   = "%s";' % group["built_for"])
        a("")
        a("using Map = std::variant<%s>;" % ", ".join(types))
        a("")
        a("/* Reads the ID register through the first alternative's accessor: the")
        a(" * ID register is a cross-revision contract, so any layout can read it")
        a(" * before the revision is known. */")
        a("inline Probe probe(std::uintptr_t base) {")
        a("    const std::uint32_t raw = %s::read_word(base, kIdOffset);" % types[0])
        a("    Probe p;")
        a("    p.raw = raw;")
        a("    p.valid = %s == kIdMagic;" % _extract("raw", idr["magic_bits"]))
        a("    p.version.major = static_cast<std::uint8_t>(%s);"
          % _extract("raw", idr["major_bits"]))
        a("    p.version.minor = static_cast<std::uint8_t>(%s);"
          % _extract("raw", idr["minor_bits"]))
        a("    return p;")
        a("}")
        a("")
        a("/* std::nullopt means: the magic did not match (no such IP at this")
        a(" * address), or no linked driver covers the reported revision. */")
        a("inline std::optional<Map> bind(std::uintptr_t base) {")
        a("    const Probe p = probe(base);")
        a("    if (!p.valid) return std::nullopt;")
        a("    const IpVersion v = p.version;")
        a("    (void)v;")
        for mapping in group["maps"]:
            a("    if (%s)  /* manifest rule %s */"
              % (version_test(mapping["match"]), mapping["match"]))
            a("        return Map{std::in_place_type<%s>, base};" % mapping["type"])
        a("    return std::nullopt;")
        a("}")
        a("")
        a("inline const char *map_name(const Map &m) {")
        a("    constexpr const char *kNames[] = {")
        for mapping in group["maps"]:
            a('        "%s",' % mapping["type"])
        a("    };")
        a("    return kNames[m.index()];")
        a("}")
        a("")
        a("/* True when the hardware reports the version this build expected. */")
        a("inline bool matches_build(std::uintptr_t base) {")
        a("    const Probe p = probe(base);")
        built = group["built_for"].split(".")
        if len(built) == 2 and all(part.isdigit() for part in built):
            a("    return p.valid && p.version.major == %s && p.version.minor == %s;"
              % (built[0], built[1]))
        else:
            a("    return p.valid;  /* %s is not a numeric major.minor */"
              % group["built_for"])
        a("}")
        a("")
        a("}  // namespace %s" % ns)
        a("")

    a("}  // namespace ipman")
    a("")
    a("#endif  /* %s */" % GUARD)
    return "\n".join(L) + "\n"
